export default [
	{
		id: 1,
		name: 'DNK Yellow Shoes',
		category: 'Men',
		image: 'sports-shoe.jpg',
		price: 150,
		discount: 20,
		rating: 3,
		options: null,
	},
	{
		id: 2,
		name: 'DNK Blue Shoes',
		category: 'Men',
		image: 'sports-shoe1.jpg',
		price: 200,
		discount: 0,
		rating: 2,
		options: [
			{
				id: 1,
				color: { name: 'blue', hex: '#1e73be' },
				price: 200,
				image: 'sports-shoe1.jpg',
			},
			{
				id: 2,
				color: { name: 'green', hex: '#81d742' },
				price: 220,
				image: 'sports-shoe2.jpg',
			},
			{
				id: 3,
				color: { name: 'red', hex: '#ce592f' },
				price: 240,
				image: 'sports-shoe3.jpg',
			},
		],
	},
	{
		id: 3,
		name: 'Dark Brown Jeans',
		category: 'Men',
		image: 'dark-brown-jeans.jpg',
		price: 150,
		discount: 0,
		rating: 4,
		options: null,
	},
	{
		id: 4,
		name: 'Blue Denim Jeans',
		category: 'Women',
		image: 'blue-denim-jeans.jpg',
		price: 150,
		discount: 0,
		rating: 3,
		options: null,
	},
	{
		id: 5,
		name: 'Basic Gray Jeans',
		category: 'Women',
		image: 'basic-gray-jeans.jpg',
		price: 150,
		discount: 0,
		rating: 4,
		options: null,
	},
	{
		id: 6,
		name: 'Blue Denim Shorts',
		category: 'Women',
		image: 'blue-denim-shorts.jpg',
		price: 150,
		discount: 15,
		rating: 2,
		options: null,
	},
	{
		id: 7,
		name: 'Anchor Bracelet',
		category: 'Accessories',
		image: 'anchor-bracelet.jpg',
		price: 150,
		discount: 0,
		rating: 3,
		options: [
			{
				id: 1,
				color: { name: 'black', hex: '#000000' },
				price: 150,
				image: 'anchor-bracelet.jpg',
			},
		],
	},
	{
		id: 8,
		name: 'Boho Bangle Bracelet',
		category: 'Accessories',
		image: 'boho-bangle-bracelet.jpg',
		price: 150,
		discount: 0,
		rating: 2,
		options: [
			{
				id: 1,
				color: { name: 'aqua', hex: '#1fb1c1' },
				price: 150,
				image: 'boho-bangle-bracelet.jpg',
			},
		],
	},
	{
		id: 9,
		name: 'Light Brown Purse',
		category: 'Accessories',
		image: 'light-brown-purse.jpg',
		price: 150,
		discount: 0,
		rating: 2,
		options: null,
	},
	{
		id: 10,
		name: 'Bright Red Bag',
		category: 'Accessories',
		image: 'bright-red-bag.jpg',
		price: 100,
		discount: 0,
		rating: 1,
		options: [
			{
				id: 1,
				color: { name: 'red', hex: '#ce592f' },
				price: 100,
				image: 'bright-red-bag.jpg',
			},
		],
	},
]
